# Generated by Django 3.0.6 on 2020-05-18 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
