# Generated by Django 3.0.6 on 2020-05-18 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_content_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
